# Default values for cpa-scraper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: true

replicaCount: 1

image:
  repository: spencerdrak/cpa-scraper
  tag: v2.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

name: cpa-scraper

schedule: "0 * * * *"

configCMName: cpa-scraper-config-yaml
credsSecretName: cpa-scraper-creds-yaml

configLocation: /app/config/cpa-scraper-config.yaml
credsLocation: /app/creds/cpa-scraper-creds.yaml

recipientList:
- email: whatever@gmail.com
  latCenter: 39
  lonCenter: -77
  maxDistance: 10
  startDate: 2020-06-01
  endDate: 2020-06-14
- email: whoever@outlook.com
  latCenter: 39
  lonCenter: -77
  maxDistance: 10
  startDate: 2020-06-01
  endDate: 2020-06-14