cpaScraper:
  email:
    testRecipient: somebody@example.com
    recipientList: 
    - email: whatever@gmail.com
      latCenter: 39
      lonCenter: -77
      maxDistance: 10
      startDate: 2020-06-01
      endDate: 2020-06-14
    - email: whoever@outlook.com
      latCenter: 39
      lonCenter: -77
      maxDistance: 10
      startDate: 2020-06-01
      endDate: 2020-06-14